routes/web.php
<?php

Route::get('/','ContactsController@index')->name('contact.index');
Route::get('/create','ContactsController@create')->name('contact.create');
Route::post('/','ContactsController@store')->name('contact.store');
Route::get('/{contact}','ContactsController@show')->name('contact.show');

app/Attachment.php
<?php

namespace App;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;

class Attachment extends Model
{
	protected $guarded = ['id'];


	public function contact()
	{
	    return $this->belongsTo('App\Contact');
	}

	public function upload(Request $request, $contactId)
	{
		if ($request->exists('photo')) {
			foreach ($request->photo as $photo) {
				$path = $photo->store('public/attachments/' . $contactId);

				(new self(['contact_id' => $contactId, 'url' => $path]))->save();
			}
		}
	}
}

app/Contact.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Contact extends Model
{
	protected $guarded = ['id'];


	public function attachments()
	{
	    return $this->hasMany('App\Attachment');
	}

	public function getFullNameAttribute()
	{
	    return $this->last_name . ' ' . $this->first_name;
	}

	public function getDiffTimeAttribute()
	{
	    return str_replace(' ', '', Carbon::parse($this->created_at)->diffForHumans());
	}

	public function getFormattedTimeAttribute()
	{
	    return Carbon::parse($this->created_at)->toDateTimeString();
	}

	public function getFullNameKanaAttribute()
	{
	    return $this->last_name_kana . ' ' . $this->first_name_kana;
	}

	public function send(Request $request)
	{
		$contact = $this->create([
			'first_name' => $request->first_name,
			'last_name' => $request->last_name,
			'first_name_kana' => $request->first_name_kana,
			'last_name_kana' => $request->last_name_kana,
			'dob' => $request->dob,
			'phone_number' => "{$request->phone_number[0]}-{$request->phone_number[1]}-{$request->phone_number[2]}",
			'body' => $request->body,
			'gender' => $request->gender,
		]);

		return $contact->id;
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContactsController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Attachment;
use Illuminate\Http\Request;
use App\Http\Requests\ContactRequest;

class ContactsController extends Controller
{
	public function index()
	{
		$contacts = Contact::select('last_name', 'first_name', 'body', 'created_at', 'id')->latest()->paginate(25);

	    return view('contacts.index', compact('contacts'));
	}

	public function create()
	{
	    return view('contacts.create');
	}

	public function store(ContactRequest $request)
	{
		$contactId = app(Contact::class)->send($request);

		app(Attachment::class)->upload($request, $contactId);

		session()->flash('message', 'お問い合わせありがとうございます');

		return redirect(route('contact.show', $contactId));
	}

	public function show(Contact $contact)
	{
		return view('contacts.show', ['contact' => $contact->load('attachments')]);
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>@yield('title')</title>
        <link rel="stylesheet" href="/css/app.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    </head>
    <body>
        <div id="app">
            @yield('content')
        </div>

        <script src="/js/app.js"></script>
        <script src="/js/dobPicker.min.js"></script>
        @stack('footer-script')
    </body>
</html>

resources/views/contacts/create.blade.php
@extends('app')

@section('content')
<main class="section">
	<div class="container">
		<div class="columns">
			<section class="column is-offset-2 is-8">
				@if ($errors->any())
					<div class="message is-danger">
						<div class="message-body">
						<ul>
							@foreach ($errors->unique() as $error)
							<li>{{ $error }}</li>
							@endforeach
						</ul>
						</div>
					</div>
				@endif
				<div class="message is-dark is-medium">
				<div class="message-header">お問い合わせ</div>
					<div class="message-body is-white">
						<form action="{{ route('contact.store') }}" method="POST" enctype="multipart/form-data">
							{{ csrf_field() }}

						<div class="field">
							<div class="columns">
								<div class="column">
									<label for="last_name" class="label">性</label>
									<p class="control">
										<input class="input" type="text" name="last_name" placeholder="山田" value="{{ old('last_name') }}" >
									</p>
								</div>
								<div class="column">
									<label for="first_name" class="label">名</label>
									<p class="control">
										<input class="input" type="text" name="first_name" placeholder="太郎" value="{{ old('first_name') }}" >
									</p>
								</div>
							</div>
						</div>

						<div class="field">
							<div class="columns">
								<div class="column">
									<label for="last_name_kana" class="label">セイ</label>
									<p class="control  is-expanded">
										<input class="input" type="text" name="last_name_kana" placeholder="ヤマダ" value="{{ old('last_name_kana') }}" >
									</p>
								</div>

								<div class="column">
									<label for="first_name_kana" class="label">メイ</label>
									<p class="control is-expanded">
										<input class="input" type="text" name="first_name_kana" placeholder="タロウ" value="{{ old('first_name_kana') }}" >
									</p>
								</div>
							</div>
						</div>

						<div class="field">
							<label for="gender" class="label">性別</label>
							<div class="control">
								<label class="radio">
								<input type="radio" name="gender" value="male" {{ old('gender') == 'male' ? 'checked' : '' }}>
									男性
								</label>
								<label class="radio">
									<input type="radio" name="gender" value="female" {{ old('gender') == 'female' ? 'checked' : '' }}>
									女性
								</label>
							</div>
						</div>

						<div class="field">
							<label for="phone_number" class="label">電話番号</label>
							<span class="help is-info">すべて半角数字で入力してください</span>
							<div class="columns">

								<div class="column">
									<p class="control">
										<input class="input" type="text" name="phone_number[]" placeholder="03"
											value="{{ old('phone_number.0') }}" >
									</p>
								</div>
								<span class="dash">
									-
								</span>
								<div class="column">
									<p class="contro">
										<input class="input" type="text" name="phone_number[]" placeholder="1111" value="{{ old('phone_number.1') }}" >
									</p>
								</div>
								<span class="dash">
									-
								</span>

								<div class="column">
									<p class="control">
										<input class="input" type="text" name="phone_number[]" placeholder="1111" value="{{ old('phone_number.2') }}" >
									</p>
								</div>
							</div>
						</div>

						<div class="field">
							<label class="label" for="dob">誕生日</label>
							<span class="help is-info">例）2010/10/02</span>
							<p><input type="text" id="datepicker" class="input" name="dob" value="{{ old('dob') }}"></p>
						</div>

						<div class="field">
							<label class="label" for="body">備考欄</label>
							<p class="control">
								<textarea class="textarea" name="body" placeholder="お問い合わせ内容をご記入ください" >{{ old('body') }}</textarea>
							</p>
						</div>

						<div class="field mb-1">
							<label for="photo" class="label">写真</label>
							<p class="control mb-half">
								<input class="input" type="file" name="photo[]">
							</p>
							<p class="control">
								<input class="input" type="file" name="photo[]">
							</p>
						</div>


						<div class="control">
							<button class="button is-medium is-fullwidth is-primary">お問い合わせ送信</button>
						</div>

						</form>
					</div>
				</div>
			</section>
		</div>
	</div>
</main>

@push('footer-script')
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/js/datepicker-ja.js"></script>

<script>
$( function() {
    $( "#datepicker" ).datepicker({
      changeMonth: true,
      yearRange : '1900:2017',
      changeYear: true
    });
  } );
</script>

@endpush

resources/views/contacts/index.blade.php
@extends('app')

@section('content')
<main class="section">
	<div class="container">
		<div class="columns">
			<div class="column is-3">
				<div class="has-text-centered">

				<a href="{{ route('contact.create') }}" class="button is-info">お問い合わせ作成</a>
				</div>
			</div>
			<div class="column is-6">
				<h1 class="title is-4">お問い合わせ一覧</h1>
				@foreach($contacts as $contact)
					<article class="media">
						<div class="media-content">
							<a href="{{ route('contact.show', ['id' => $contact->id]) }}">
								{{ $contact->full_name }}さんからのお問い合わせ
							</a>
							<span class="help is-info is-marginless">{{ $contact->diff_time }}</span>
							@if($contact->body)
								{{ str_limit($contact->body) }}
							@endif
						</div>
					</article>
				@endforeach

				<div class="section">
				{{ $contacts->links() }}

				</div>
			</div>
		</div>
	</div>
</main>
@endsection

resources/views/contacts/show.blade.php
@extends('app')

@section('content')
<main class="section">
	<div class="container">
		<div class="columns">
			<article class="column is-offset-2 is-8">
				@if(session()->has('message'))
					<div class="message is-success">
						<div class="message-body">
							<span class="help is-success title is-6">
								{{ session()->get('message') }}
							</span>
						</div>
					</div>
				@endif
				<div class="mb-1">
					<a href="{{ route('contact.index') }}" class="is-size-4">お問い合わせ一覧へ</a>
				</div>
				<h1 class="title is-3">お問い合わせ詳細</h1>

				<h2 class="title is-5 is-marginless">送信日時</h2>
				<p class="mb-1">
					{{ $contact->formatted_time }}
				</p>

				<h2 class="title is-5 is-marginless">名前</h2>
				<p class="mb-1">
					{{ $contact->full_name }}
				</p>

				<h2 class="title is-5 is-marginless">カナ</h2>
				<p class="mb-1">
					{{ $contact->full_name_kana }}
				</p>

				<h2 class="title is-5 is-marginless">性別</h2>
				<p class="mb-1">
					{{ $contact->gender == 'male' ? '男性' : '女性' }}
				</p>

				<h2 class="title is-5 is-marginless">電話番号</h2>
				<p class="mb-1">
					{{ $contact->phone_number }}
				</p>

				<h2 class="title is-5 is-marginless">誕生日</h2>
				<p class="mb-1">
					{{ \Carbon\Carbon::parse($contact->dob)->format('Y年m月d日') }}
				</p>

				@if($contact->body)
				<h2 class="title is-5 is-marginless">備考</h2>
				<p class="mb-1">
					{!! nl2br(e($contact->body)) !!}
				</p>
				@endif

				@if(count($contact->attachments))
				<h2 class="title is-5 mb-1 is-marginless">写真</h2>
				<p class="mb-1">
					@foreach($contact->attachments as $attachment)
						<figure class="image mb-1">
							<img src="{{ Storage::url($attachment->url) }}">
						</figure>
					@endforeach
				</p>
				@endif

				<div class="">
					<a href="{{ route('contact.index') }}" class="is-size-3">お問い合わせ一覧へ</a>
				</div>
			</article>
		</div>
	</div>
</main>
@endsection

resources/views/home.blade.php
@extends('app')

@section('content')
<main class="section">
	<div class="container">
		<div class="columns">
			<section class="column is-offset-2 is-8">
				@if ($errors->any())
					<div class="message is-danger">
						<div class="message-body">
						<ul>
							@foreach ($errors->unique() as $error)
							<li>{{ $error }}</li>
							@endforeach
						</ul>
						</div>
					</div>
				@endif
				<div class="message is-dark is-medium">
				<div class="message-header">お問い合わせ</div>
					<div class="message-body is-white">
						<form action="{{ route('contact.store') }}" method="POST" enctype="multipart/form-data">
							{{ csrf_field() }}

						<div class="field">
							<div class="columns">
								<div class="column">
									<label for="last_name" class="label">性</label>
									<p class="control">
										<input class="input" type="text" name="last_name" placeholder="山田" value="{{ old('last_name') }}" >
									</p>
								</div>
								<div class="column">
									<label for="first_name" class="label">名</label>
									<p class="control">
										<input class="input" type="text" name="first_name" placeholder="太郎" value="{{ old('first_name') }}" >
									</p>
								</div>
							</div>
						</div>

						<div class="field">
							<div class="columns">
								<div class="column">
									<label for="last_name_kana" class="label">セイ</label>
									<p class="control  is-expanded">
										<input class="input" type="text" name="last_name_kana" placeholder="ヤマダ" value="{{ old('last_name_kana') }}" >
									</p>
								</div>

								<div class="column">
									<label for="first_name_kana" class="label">メイ</label>
									<p class="control is-expanded">
										<input class="input" type="text" name="first_name_kana" placeholder="タロウ" value="{{ old('first_name_kana') }}" >
									</p>
								</div>
							</div>
						</div>

						<div class="field">
							<label for="gender" class="label">性別</label>
							<div class="control">
								<label class="radio">
								<input type="radio" name="gender" value="male" {{ old('gender') == 'male' ? 'checked' : '' }}>
									男性
								</label>
								<label class="radio">
									<input type="radio" name="gender" value="female" {{ old('gender') == 'female' ? 'checked' : '' }}>
									女性
								</label>
							</div>
						</div>

						<div class="field">
							<label for="phone_number" class="label">電話番号</label>
							<span class="help is-info">すべて半角数字で入力してください</span>
							<div class="columns">

								<div class="column">
									<p class="control">
										<input class="input" type="text" name="phone_number[]" placeholder="03"
											value="{{ old('phone_number.0') }}" >
									</p>
								</div>
								<span class="dash">
									-
								</span>
								<div class="column">
									<p class="contro">
										<input class="input" type="text" name="phone_number[]" placeholder="1111" value="{{ old('phone_number.1') }}" >
									</p>
								</div>
								<span class="dash">
									-
								</span>

								<div class="column">
									<p class="control">
										<input class="input" type="text" name="phone_number[]" placeholder="1111" value="{{ old('phone_number.2') }}" >
									</p>
								</div>
							</div>
						</div>

						<div class="field">
							<label class="label" for="dob">誕生日</label>
							<span class="help is-info">例）2010/10/02</span>
							<p><input type="text" id="datepicker" class="input" name="dob" value="{{ old('dob') }}"></p>
						</div>

						<div class="field">
							<label class="label" for="body">備考欄</label>
							<p class="control">
								<textarea class="textarea" name="body" placeholder="お問い合わせ内容をご記入ください" >{{ old('body') }}</textarea>
							</p>
						</div>

						<div class="field mb-1">
							<label for="photo" class="label">写真</label>
							<p class="control mb-half">
								<input class="input" type="file" name="photo[]">
							</p>
							<p class="control">
								<input class="input" type="file" name="photo[]">
							</p>
						</div>


						<div class="control">
							<button class="button is-medium is-fullwidth is-primary">お問い合わせ送信</button>
						</div>

						</form>
					</div>
				</div>
			</section>
		</div>
	</div>
</main>

@push('footer-script')
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/js/datepicker-ja.js"></script>

<script>
$( function() {
    $( "#datepicker" ).datepicker({

      changeMonth: true,
      yearRange : '1900:2017',
      changeYear: true
    });
  } );
</script>

@endpush